before:
  hooks:
    - go mod tidy
builds:
  - id: nurse
    binary: nurse
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - ids:
      - nurse
    image_templates:
      - ghcr.io/baez90/nurse:latest
      - ghcr.io/baez90/nurse:{{ .Tag }}
      - ghcr.io/baez90/nurse:{{ .Major }}
      - ghcr.io/baez90/nurse:{{ .ShortCommit}}
    dockerfile: deployments/Dockerfile
